services:
  redis:
    image: redis:8.8.0-alpine
    container_name: redis-lab
    ports:
      - "26379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5